### ISSUE TITLE
Return 201 success to solve duplicate tree entries

### ISSUE THREAD

**Issue by dezidaisy** [Greenstand/treetracker-mobile-api#9]
We now send a 'uuid' field with each new tree JSON.  If this UUID matches a UUID already stored in the database, do not insert a new tree record and return 201.  This solves duplicate trees.

UUID also needs to be saved into a UUID column when a new tree is saved.  The UUID column will need to be created in a database migration.

**Comment by deepwinter** [comment]
@bittricky here is an example of an API integration test using supertest

```
require('module-alias/register');
const server = require('./server');
const app = server.app.listen(3000);

const assert = require('chai').assert;
const request = require('supertest');
const sinon = require("sinon");

describe('Trees API', () => {

  it('POST /tree', (done) => {
    request(app)
      .post('/onboard')
      .send(
        {
          uuid: 'asdf-asdf-asdf'
         }
      )
      .expect(201)
      .end(function(err, res) {
       if (err) return done(err);
       done();
     });
  });

```


});

**Comment by deepwinter** [comment]
Super work @bittricky !
